### ISSUE TITLE
Clicking on "I am link" closes the Create Theme dialog box abruptly

### ISSUE THREAD

**Issue by chinmaykunkikar** [atapas/theme-builder#2]
It also resets the app, hence failing to save the theme.

Using ```href="#"``` for placeholder link might solve this.
https://github.com/atapas/theme-builder/blob/2298500a3316afb36c76dd8b09dfca1d310a7700/src/CreateThemeContent.js#L151

**Comment by atapas** [comment]
Thanks @chinmaykunkikar for creating the issue. Shall take care!

**Comment by atapas** [comment]
Opened a PR. It's in testing now.

**Comment by atapas** [comment]
@all-contributors please add @chinmaykunkikar  for bug

**Comment by atapas** [comment]
@chinmaykunkikar,

You have been added as a contributor to this project. Thanks for making it better. Please feel free to contribute in the future to code, issue, doc, etc.

![image](https://user-images.githubusercontent.com/3633137/105624519-4698b000-5e48-11eb-9050-fb23e8f51087.png)
