### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by eddiejaoude** [atapas/theme-builder#8]
**Having a Code of Conduct makes a project more inclusive and more people will want to get involved.**

A good [Code ofConduct](https://www.contributor-covenant.org)

<img width="3164" alt="Screenshot 2021-01-24 at 12 05 41" src="https://user-images.githubusercontent.com/624760/105629736-abe6a400-5e3c-11eb-816e-4b1b0ca4d130.png">

**Comment by atapas** [comment]
@eddiejaoude, This is actually great! Thanks. I have added it now. Do you have any suggestions for a good Contributing template for this kind of project?

**Comment by atapas** [comment]
@all-contributors please add @eddiejaoude  for bug
